import { Inter } from "next/font/google";
import "./globals.css";

import Providers from "./Providers";

import Header from "@/components/Header";
import Tabs from "@/components/Tabs";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Movie App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Providers>
          <Header />
          <Tabs/>
          {children}
        </Providers>
      </body>
    </html>
  );
}
